apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual greeting

on:
  workflow_dispatch: {}

jobs:
  greet:
    steps:
    - name: greet
      uses: docker://alpine:3.20
      run: echo "manual hello there"
