apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: schedule greeting

on:
  schedule:
    - cron: "invalid-cron"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  greet:
    steps:
    - name: greet
      uses: docker://alpine:3.20
      run: echo "hello there"
